# Beta distribution from scipy...
# importing beta from scipy.stats...
from scipy.stats import beta

# number of success...
a = 8

# number of failure...
b = 2

# derive a and b...
p = beta.cdf(.90, a, b)

# print p...
print(p)

# substracting to get a right area in beta distribution...8
# Beta distribution from scipy...
# importing beta from scipy.stats...
from scipy.stats import beta

# number of success...
a = 8

# number of failure...
b = 2

# derive a and b...
# substracting 1.0 from beta.cdf...
p =1.0 - beta.cdf(.90, a, b)

# print p...
print(p)

# Beta distribution with more trails...
# importing beta from scipy.stats...
from scipy.stats import beta

# number of success...
a = 30

# number of failure...
b = 6

# derive a and b...
# distributing beta with more trails...
p = 1.0 - beta.cdf(.90, a, b)

# print p...
print(p)

# Beta distribution with middle area using scipy...
# importing beta from scipy.stats...
from scipy.stats import beta

# number of success...
a = 8

# number of failure...
b = 2

# derive a and b...
# distributing beta with using middle area.
p = beta.cdf(.90, a, b) - beta.cdf(.80, a, b)

# print p...
print(p)