# Binomial Distribution from scipy...
# importing binom from scipy.stats...
from scipy.stats import binom

# number of trails...
n = 10

# number of probability...
p = 0.9

# k for number of sucess for (n + 1):...
for k in range(n + 1):
    
# derive probability variables...
    probability = binom.pmf(k, n, p)
    
# print "{0} - {1}".format(k, probability ...
    print("{0} - {1}".format(k, probability))